# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a58bcfe8d597b8b080821cf5884e1ca989ee7a8edf1cb51991046dcbb67fe26ff3156cdeaad2f3c50b38e9c487d1a005d276994bf8aa5882f903bfb79a2aee0

test:
  secret_key_base: 6e64c6b60fd431fad2e7dbd9933d3e4b6708e391a4a1cf170607934835025befdf3fa139d5947defbe5c10581b98ca6f2b2912b664162ac96013dc1dacbb0dd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
